# Generated by Django 5.2.5 on 2025-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(blank=True, to='members.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
